In [1]:
import torch

#### Function 1: `torch.randn`

This function generates a tensor consisting of random  numbers sampled from a Standard Normal Distribution (mean=0, std=1). The function accepts the following arguments, let's look at them one by one:

- `size`: The size of the resultant tensor, usually defined as a `list` or a `tuple`
- `out`: This optional argument lets you specify where the resultant tensor has to be stored, this must be a Torch tensor (otherwise, it either throws an error or never assigns the value). By default, the argument is set to `None` and in which case, the object returned will have to be explicitly assigned to a variable
- `dtype`: The type for the resultant tensor can be specified here (optionally). By default, it is set to `None` and in which case, the global default tensor type would be set
- `layout`: Optional argument to specify the desired layout for the resultant tensor. By default, this arg is set to `torch.strided`. More on `torch.strided` in the below section
- `device`: Optional argument to specify the desired device to attach the tensor instance to. Defaults to `None` and can be specified using `torch.device()` for CPU/GPU
- `requires_grad`: This is a boolean argument set to `False` by default. Specifies if the different operations on this tensor have to be recorded. If `True`, all operations would be recorded for Torch to calculate the gradient (using autograd). This is relevant during the backward pass / back propagation in a Neural Net training.

**Possible application**: This is normally used for randomly generating tensors to initialize parameters or even inputs in certain cases.

In [2]:
# working example

temp = torch.Tensor()
torch.randn(size=[2,4], out=temp)

tensor([[-0.9656, -0.5504,  0.6922,  0.3452],
        [-0.7286, -0.4964,  0.1163,  0.1918]])

In [3]:
temp

tensor([[-0.9656, -0.5504,  0.6922,  0.3452],
        [-0.7286, -0.4964,  0.1163,  0.1918]])

The variable `temp` was initialized as a tensor and hence it'd receive the random tensor by assignment. However, if the variable is of incompatible type the operation would throw an error. Particularly, for `None` type, the assignment never happens although no error is thrown.

In [4]:
# bad example

some_variable = None
torch.randn(size=[2,4], out=some_variable)

tensor([[ 0.7126,  0.2565, -0.8528, -0.4314],
        [ 1.2556,  0.7384,  0.9697,  0.9443]])

In [5]:
# bad example output
# the variable is never set
print(some_variable)

None


**A note on strides**: 

`torch.strided` is responsible for deciding the memory layout of tensors.

To explain in simple words, we need to take a step back and look at tensors. Clearly, a tensor is a multi-dimensional representation of values (numeric, in this context) and these values require to be stored in some location in memory. 
But how are they represented in memory ? The answer is that there'd be a memory layout that's associate with the tensor. But who takes care of them ? Strides. 

Strides would provide a list of integers that help in calculating the jumps in memory locations to access the different values of a tensor (please bear in mind that the tensor values may not be allocated contiguous memory locations). 

Now, coming back to PyTorch, the default memory layout representation is taken care by `torch.strided`, which is a dense tensor representation. However, there's a sparse representation (experimental) support which is available too.

#### Function 2: `torch.reshape` 

The `reshape` function takes in an input tensor and alters its shape as specified.
Looking at the arguments,

- `input`: Should be a valid tensor. The reshape would either provide a "view" of the tensor (no copy) if possible, otherwise returns a copy of the reshaped tensor
- `shape`: The new shape to which the input tensor has to be changed. This has to be a valid shape, otherwise the function would throw an error. A valid shape would stay true to its dimension - meaning it should be possible to arrange the number of elements properly (see the bad example provided below)

**Possible application**: Reshape is a very handy functionality used during tensor multiplication operation that may arise while creating neural nets from scratch, calculating back-prop errors, etc.

In [6]:
# working example
torch.reshape(input=temp, shape=(4,2))

tensor([[-0.9656, -0.5504],
        [ 0.6922,  0.3452],
        [-0.7286, -0.4964],
        [ 0.1163,  0.1918]])

In [7]:
# bad example
torch.reshape(input=temp, shape=(3,3))

RuntimeError: shape '[3, 3]' is invalid for input of size 8

#### Function 3: `torch.argmax`

This function returns the index of the maximum value among all the elements in the tensor.

Following are the arguments allowed:
- `input`: The input tensor is to be provided here
- `dim`: This optional argument expects an integer input that specifies the dimension along which the max is to be found out. Depending on the input dimension, the input tensor would be reduced to a resultant form. See below example for more clarity. If the argument is `None`, the input is assumed as a flattened tensor
- `keepdim`: This is a boolean flag that decides whether to retain the tensor dimension. This argument would be ignored if the `dim` argument is `None`. 

Note that for a given tensor, there's also an attribute function of `argmax`.

**Possible application**: This is a reduce operation that's useful while we look at prediction probabilities in a multi-class classification problem, where usually the output would be a prediction vector. This would let us zero-in on the relevant part.

In [8]:
# working example

print("temp:\n{}".format(temp))

print("\ntorch.argmax(temp) is: {}".format(torch.argmax(temp).item()))

print("\ntorch.argmax(temp, dim=1)\ngives the argmax across the first dimension,i.e row1 and row2: \n{}".
      format(torch.argmax(temp, dim=1)))

print(
    "\ntorch.argmax(temp, dim=1, keepdim=True)\ngives the argmax across the first dimension (retaining the input dimensions): \n{}".
      format(torch.argmax(temp, dim=1, keepdim=True)))

temp:
tensor([[-0.9656, -0.5504,  0.6922,  0.3452],
        [-0.7286, -0.4964,  0.1163,  0.1918]])

torch.argmax(temp) is: 2

torch.argmax(temp, dim=1)
gives the argmax across the first dimension,i.e row1 and row2: 
tensor([2, 3])

torch.argmax(temp, dim=1, keepdim=True)
gives the argmax across the first dimension (retaining the input dimensions): 
tensor([[2],
        [3]])



**How does the `dim` argument work ?**
A tensor is essentially a multi-dimensional array. Each dimension represents an axis here.

For simplicity, let's consider the 2D Tensor as an example,

            Column axis (axis=1)
         ------------------------------------->
         [[-1.1083,  1.7481,  0.4163,  1.3754],
         [-0.5549,  0.3910,  0.8286, -1.1974]]
        

Here, it consists of only 2 axes - the row axis and column axis. The row axis let's us traverse along the rows (vertical) in a tensor, while the column axis takes us along the columns (horizontal).

To summarize,

`axis=0` represents the row axis.

`axis=1` represents the column axis.

Furthermore, as the dimensions of the tensor increases (3D Tensors, or higher) they'll have additional axis/es for traversal.

Below is a bad example, where the axis dimensions are incorrectly defined while using `argmax`.

In [9]:
# bad example

print("\ntorch.argmax(temp, dim=1)\ngives the argmax across the second dimension,i.e row1 and row2: \n{}".
      format(torch.argmax(temp, dim=2)))

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

Similar functions:

- `torch.argmin`
- `torch.min` and `torch.max`

#### Function 4: `torch.abs`

The function returns the absolute valuefor a given input tensor. This accepts an input tensor as an argument and optionally an output tensor to which the result would go.

About the arguments,

- `input`: The input tensor
- `out`: The tensor to which the output would be assigned.

Here, one should ensure that the `out` argument receives a valid/correctly initialized tensor. Otherwise, the returned result won't be assigned.

**Potential application:** During calculation of evaluation metrics like certain loss functions during training, there'd be operations on top of the absolute values of the vectors/tensors.

In [10]:
# working example
abs_temp = torch.Tensor()

print(temp)

torch.abs(input=temp, out=abs_temp)
print("\n")
print(abs_temp)

tensor([[-0.9656, -0.5504,  0.6922,  0.3452],
        [-0.7286, -0.4964,  0.1163,  0.1918]])


tensor([[0.9656, 0.5504, 0.6922, 0.3452],
        [0.7286, 0.4964, 0.1163, 0.1918]])


In [11]:
# bad example

some_tensor = None

print(temp)

torch.abs(input=temp, out=some_tensor)

print(some_tensor)

tensor([[-0.9656, -0.5504,  0.6922,  0.3452],
        [-0.7286, -0.4964,  0.1163,  0.1918]])
None


#### Function 5: `torch.add`

This function adds a scalar to each element of a given input tensor and returns the new tensor as output.
Here, the type of scalar should be compatible with that of the intput tensor.

Following are the arguments taken by `torch.add`:

- `input`: The input tensor
- `other`: The scalar that would be added to the given tensor

**Potential applications**: If one is trying to implement certain optimization techniques from scratch (like, Gradient Descent), there would steps involving scalar updates to the parameters.

In [12]:
# working example

bad = torch.Tensor()
scalar_float = 7.

torch.add(abs_temp,other=scalar_float, out=None)

tensor([[7.9656, 7.5504, 7.6922, 7.3452],
        [7.7286, 7.4964, 7.1163, 7.1918]])

Below is an incorrect operation where `other` argument doesn't receive a scalar value.

In [13]:
# bad example

torch.add(abs_temp, other=bad, out=None)

RuntimeError: The size of tensor a (4) must match the size of tensor b (0) at non-singleton dimension 1